[application]
name = "kstars"
default_platform = "web"
out_dir = "dist"
asset_dir = "public" 

[web.app]

# HTML title tag content
title = "kstars: Top GitHub Repos"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.watcher]
watch_path = ["src", "public", "data"]
reload_html = true
